-- Migration 002: Media Vault
-- Every asset generated by Seedream, Klipy, or uploaded by a user is indexed here.
-- Kimi K2.5 auto-tags each asset so it can be searched by natural language.

CREATE TABLE IF NOT EXISTS media_assets (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         TEXT NOT NULL,
    url             TEXT NOT NULL,
    type            TEXT NOT NULL CHECK (type IN ('image', 'video', 'gif')),
    ai_description  TEXT,
    tags            TEXT[] DEFAULT '{}',
    source          TEXT NOT NULL CHECK (source IN ('seedream', 'klipy', 'upload', 'remotion')),
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast per-user vault lookups
CREATE INDEX IF NOT EXISTS idx_media_assets_user_id ON media_assets(user_id);

-- Index for fast full-text search on description + tags
CREATE INDEX IF NOT EXISTS idx_media_assets_description ON media_assets USING gin(to_tsvector('english', ai_description));
CREATE INDEX IF NOT EXISTS idx_media_assets_tags ON media_assets USING gin(tags);
