export interface VisualBrain {
    id: string;
    identity: string;
    brandTraits: string[];
    audience: string;
    voiceStyle: string;
    colorPalette: { primary: string; secondary: string; accent: string; background: string };
    typography: { headline: string; body: string; cta: string };
    contentRules: { hookStyle: string; ctaStyle: string; rhythm: string };
    updated_at: string;
}

// ─── Media Vault (Sprint 7) ──────────────────────────────────────────────────
// Every asset ever generated by Seedream/Klipy/uploads is stored here.
// Kimi K2.5 auto-tags each one so users can search by natural language.
export interface MediaAsset {
    id: string;
    user_id: string;
    url: string;
    type: 'image' | 'video' | 'gif';
    /** AI-generated plain English description e.g. "female patient in clinic chair" */
    ai_description: string;
    /** Extracted keyword tags e.g. ["medical", "female", "b-roll"] */
    tags: string[];
    source: 'seedream' | 'klipy' | 'upload' | 'remotion';
    created_at: string;
}

export interface UserProfile {
    id: string;
    email: string;
    full_name?: string;
    avatar_url?: string;
    plan: "Free" | "Pro" | "Enterprise";
    visual_brain_id?: string; // Links to the persistent Visual Brain instruction set
}

export interface VideoProject {
    id: string;
    user_id: string;
    title: string;
    description?: string;
    status: "draft" | "processing" | "completed" | "failed";
    created_at: string;
    updated_at: string;
    thumbnail_url?: string;
    video_url?: string;
}

export interface Character {
    id: string;
    user_id: string;
    name: string;
    description?: string;
    reference_image_path?: string;
    generated_images: string[];
    parameters: Record<string, any>;
    created_at: string;
}

export interface DashboardStats {
    videosCreated: number;
    charactersCreated: number;
    plan: string;
}

// ─── Sprint 6: Social Publishing ─────────────────────────────────────────────

export type SocialPlatform = 'tiktok' | 'youtube' | 'instagram';

export interface SocialAccount {
    id: string;
    user_id: string;
    platform: SocialPlatform;
    platform_user_id?: string;
    platform_username?: string;
    platform_avatar_url?: string;
    /** Never exposed to UI — only used server-side */
    access_token?: string;
    token_expires_at?: string;
    is_active: boolean;
    created_at: string;
    updated_at: string;
}

export interface ScheduledPost {
    id: string;
    user_id: string;
    idea: string;
    caption: string;
    thumbnail_url?: string;
    /** S3 URL of the rendered MP4 from Remotion Lambda */
    video_url: string;
    /** ISO date string e.g. "2026-04-15" */
    scheduled_date: string;
    /** 24-h time string e.g. "14:30" */
    scheduled_time: string;
    status: 'scheduled' | 'published' | 'failed';
    /** Array of SocialPlatform keys */
    platforms: SocialPlatform[];
    publish_result?: Record<string, string>;
    error_message?: string;
    retry_count: number;
    created_at: string;
    published_at?: string;
}

export interface PublishJobResult {
    platform: SocialPlatform;
    success: boolean;
    post_id?: string;
    url?: string;
    error?: string;
}

export interface VideoState {
    id: string; // Ties back to VideoProject.id
    global: {
        fps: number;
        durationInFrames: number;
        width: number;
        height: number;
        backgroundColor?: string;
    };
    audio: {
        voiceoverUrl?: string; // Qwen3-TTS audio
        bgmUrl?: string; // ACE-Step 1.5 music
        volumeBgm: number;
    };
    captions: {
        text: string;
        startFrame: number;
        endFrame: number;
    }[];
    scenes: {
        id: string;
        startFrame: number;
        durationInFrames: number;
        transitionType?: 'fade' | 'slide' | 'none';
        visualType: 'image' | 'video' | 'gif';
        visualUrl: string; // Seedream image / Tenor GIF URL
        kenBurnsEffect?: boolean;
        kenBurnsDirection?: 'zoom_in' | 'zoom_out' | 'pan_left' | 'pan_right';
    }[];
}
